// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_gScug1ACA2fE_HcG4KPoIERMvFR2FDg',
    appId: '1:684980547065:web:d7d8ee2ebaecf478362128',
    messagingSenderId: '684980547065',
    projectId: 'entradas-4350a',
    authDomain: 'entradas-4350a.firebaseapp.com',
    storageBucket: 'entradas-4350a.appspot.com',
    measurementId: 'G-DD4ZKM3YF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7typACDYdqSAUJjUYg_7YM6QgaLCi7xo',
    appId: '1:684980547065:android:c4f60ae9626e4880362128',
    messagingSenderId: '684980547065',
    projectId: 'entradas-4350a',
    storageBucket: 'entradas-4350a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUxwGpSkkeMVUhCaqFrOlvOIN36epmSYs',
    appId: '1:684980547065:ios:4c1e87e9342ab581362128',
    messagingSenderId: '684980547065',
    projectId: 'entradas-4350a',
    storageBucket: 'entradas-4350a.appspot.com',
    iosBundleId: 'com.example.entradasSalidas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_gScug1ACA2fE_HcG4KPoIERMvFR2FDg',
    appId: '1:684980547065:web:59329d83cf89df3f362128',
    messagingSenderId: '684980547065',
    projectId: 'entradas-4350a',
    authDomain: 'entradas-4350a.firebaseapp.com',
    storageBucket: 'entradas-4350a.appspot.com',
    measurementId: 'G-EZDY1WQ7R4',
  );
}
